### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by unovalegends** [Zerthick/CoinPurse#1]
I been trying to use this plugin but its not working.

Here my error
https://hastebin.com/utefuyuwuw.vbs

**Comment by Zerthick** [comment]
What version of Sponge are you running?

**Comment by unovalegends** [comment]
sponge 1.10.2

**Comment by Zerthick** [comment]
Well there's your problem, CoinPurse is only compatible with Sponge API 6 (Minecraft 1.11.2) and above. 😛

**Comment by unovalegends** [comment]
Any way you can get it for 1.10.2?

**Comment by Zerthick** [comment]
Not likely, custom data (which this plugin relies on) was changed quite a
bit in subsequent revisions of the API.  It may be possible to do a
backport, however considering Sponge API versions 5 & 6 are no longer being
actively developed there would need to be considerable demand for me to
consider investing the time to rework the plugin to older versions of the
API.
