### ISSUE TITLE
Dupli with negative number !

### ISSUE THREAD

**Issue by Flashback083** [Zerthick/CoinPurse#2]
Hello ! I use the last version of CoinPurse, and my players just constate that /cp -10000 give 10 000 money ! The coinpurse is -10000 so if it be use, it remove the money but they can just /cp -100000 and drop the purse, the player will have xxxx money with /balance T..T

**Comment by Zerthick** [comment]
Well that's no good!

**Comment by Zerthick** [comment]
Should be fixed in: https://github.com/Zerthick/CoinPurse/releases/tag/v1.2.1
